// inl4/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AuthService } from './auth.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
  constructor(public authService: AuthService) {
    if(authService.authenticated) {
      this.username = authService.user
    }
  }
  username: any;

  login(credentials) {
    this.authService.login({credentials})
    this.username = authService.user
  }

  logout() {
    this.authService.logout()
    this.username = authService.user
  }

  testApi() {
    this.authService.getResource('friends')
  }
}

<div class="container">
  
  <!-- Complete this markup for showing error upon unsuccessful login. -->
  <p class="error">Login credentials were incorrect!</p>

  <!-- Complete this markup for showing the status bar correctly, depending on whether or not the user is authenticated. -->
  <div class="status">
    <span>User ID: </span>
    <button (click)="testApi()">Test API</button>
    <button (click)="logout()">Logout</button>
  </div>

  <!-- Add markup for showing the login form if the user is not authenticated. -->
  <div *ngIf="!token">
    <p *ngIf="error" class="error">Login credentials were incorrect!</p>

  <form
    (ngSubmit)="login(f.value)"
    #f="ngForm"
  >
    <div class="form-group">
      <label for="username"> Please enter your username</label>
      <input
        type="text"
        name="username"
        id="username"
        class="form-control"
        placeholder="Enter username..."

        ngModel
        #username="ngModel"

        required
      >
    </div>
    <div class="form-group">
      <label for="password"> Please enter your password</label>
      <input
        type="text"
        name="password"
        id="password"
        class="form-control"
        placeholder="Enter password..."

        ngModel
        #password="ngModel"

        required
        minlength="8"
      >
    </div>
  <button
  type="submit"
  [disabled]="!f.valid"
  >Log in</button>
  </form>
  </div>
</div>
</div>

// inl4/react/src/App.js
import React, { Component } from 'react';


import Login from './Login';

class App extends Component {
    // get the initial state from AuthService. 
    state = AuthService.getAuthState();

    // ...

    login = (username, password) => {
        // login the user with the given credentials and update the component state upon success or failure respectively.
        AuthService.login({ username, password })

            .catch(error => {
                console.log(error)
                this.loginFail = true
            })
            .then(() => {
                this.setState(AuthService.getAuthState())
                this.loginFail = false
            })

    };

    logout = () => {
        // logout the user and update the component with state given by AuthService.
        AuthService.logout()
        this.setState(AuthService.getAuthState())
    };

    testApi() {
        // test access to a protected API route and log the results.
        AuthService.getResource('friends')
            .then((res) => {
                console.log('friends: ', res)
            })
            .catch(error => {
                console.log('error message: ', error)
            })
    }

    // ...

    render() {
        // complete the JSX code below to show the proper markup depending on whether or not the user has been authenticated.
        if (this.state.isLoggedIn) {
            return (
                <div className="container">

                    <div className="status">
                        <span>User ID: {this.state.name}</span>
                        <button onClick={this.testApi}>Test API</button>
                        <button onClick={this.logout}>Logout</button>
                    </div>
                </div>
            );
        } else {
            return (
                <div className="container">

                    {this.loginFail ? <p className="error">Login credentials were incorrect!</p> : <p></p>}

                    <div className="status">
                        <span>User ID: N/A</span>
                        <button onClick={this.testApi}>Test API</button>

                    </div>

                    < Login onLogin={this.login} />

                </div>
            );
        }
    }
}

export default App;
